name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Build and push Main web app container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERUSERNAME }}/tools-image:v2.0.0
        file: ./Dockerfile
    # second try



